--    new -- autogenerated lush spec on qua 01 jun 2022 12:20:13
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function()
	return {
		SpecialKey({ fg = "cyan" }), -- SpecialKey     xxx ctermfg=81 guifg=Cyan
		TermCursor({ gui = "reverse" }), -- TermCursor     xxx cterm=reverse gui=reverse
		NonText({ bg = "grey30", gui = "bold", fg = "lightblue" }), -- NonText        xxx ctermfg=81 gui=bold guifg=LightBlue guibg=grey30
		EndOfBuffer({ NonText }), -- EndOfBuffer    xxx links to NonText
		Whitespace({ NonText }), -- Whitespace     xxx links to NonText
		Directory({ fg = "cyan" }), -- Directory      xxx ctermfg=159 guifg=Cyan
		netrwDir({ Directory }), -- netrwDir       xxx links to Directory
		ErrorMsg({ bg = "red", fg = "white" }), -- ErrorMsg       xxx ctermfg=15 ctermbg=1 guifg=White guibg=Red
		NvimInvalidSpacing({ ErrorMsg }), -- NvimInvalidSpacing xxx links to ErrorMsg
		IncSearch({ gui = "reverse" }), -- IncSearch      xxx cterm=reverse gui=reverse
		Search({ bg = "yellow", fg = "black" }), -- Search         xxx ctermfg=0 ctermbg=11 guifg=Black guibg=Yellow
		QuickFixLine({ Search }), -- QuickFixLine   xxx links to Search
		Substitute({ Search }), -- Substitute     xxx links to Search
		MoreMsg({ gui = "bold", fg = "seagreen" }), -- MoreMsg        xxx ctermfg=121 gui=bold guifg=SeaGreen
		ModeMsg({ gui = "bold" }), -- ModeMsg        xxx cterm=bold gui=bold
		LineNr({ fg = "#99ff99" }), --{ ctermfg=21, guifg=Red}, -- LineNr         xxx ctermfg=11 guifg=Yellow
		LineNrAbove({ fg = "#ff9966" }), -- LineNrAbove    xxx links to LineNr
		LineNrBelow({ fg = "#ffff99" }), -- LineNrBelow    xxx links to LineNr
		CursorLineNr({ LineNr }), -- CursorLineNr   xxx cterm=underline ctermfg=11 gui=bold guifg=Yellow
		Question({ gui = "bold", fg = "green" }), -- Question       xxx ctermfg=121 gui=bold guifg=Green
		netrwSymLink({ Question }), -- netrwSymLink   xxx links to Question
		StatusLine({ term = "reverse", ctermbg = 5, gui = "undercurl", guisp = "Magenta" }), -- gui = "red,bold,reverse" }), -- StatusLine     xxx cterm=bold,reverse gui=bold,reverse
		MsgSeparator({ StatusLine }), -- MsgSeparator   xxx links to StatusLine
		StatusLineNC({ gui = "reverse" }), -- StatusLineNC   xxx cterm=reverse gui=reverse
		VertSplit({ gui = "reverse" }), -- VertSplit      xxx cterm=reverse gui=reverse
		WinSeparator({ VertSplit }), -- WinSeparator   xxx links to VertSplit
		Title({ gui = "bold", fg = "magenta" }), -- Title          xxx ctermfg=225 gui=bold guifg=Magenta
		Visual({ bg = "#eb4255" }), -- Visual         xxx ctermbg=0 guibg=grey60
		WarningMsg({ fg = "red" }), -- WarningMsg     xxx ctermfg=224 guifg=Red
		netrwCoreDump({ WarningMsg }), -- netrwCoreDump  xxx links to WarningMsg
		WildMenu({ bg = "yellow", fg = "black" }), -- WildMenu       xxx ctermfg=0 ctermbg=11 guifg=Black guibg=Yellow
		Folded({ bg = "lightgrey", fg = "darkblue" }), -- Folded         xxx ctermfg=4 ctermbg=7 guifg=DarkBlue guibg=LightGrey
		netrwData({ Folded }), -- netrwData      xxx links to Folded
		netrwGray({ Folded }), -- netrwGray      xxx links to Folded
		FoldColumn({ bg = "grey", fg = "darkblue" }), -- FoldColumn     xxx ctermfg=4 ctermbg=7 guifg=DarkBlue guibg=Grey
		CursorLineFold({ FoldColumn }), -- CursorLineFold xxx links to FoldColumn
		DiffAdd({ bg = "darkblue" }), -- DiffAdd        xxx ctermbg=4 guibg=DarkBlue
		DiffChange({ bg = "darkmagenta" }), -- DiffChange     xxx ctermbg=5 guibg=DarkMagenta
		netrwLib({ DiffChange }), -- netrwLib       xxx links to DiffChange
		netrwMakefile({ DiffChange }), -- netrwMakefile  xxx links to DiffChange
		DiffDelete({ bg = "darkcyan", gui = "bold", fg = "blue" }), -- DiffDelete     xxx ctermfg=12 ctermbg=6 gui=bold guifg=Blue guibg=DarkCyan
		DiffText({ bg = "red", gui = "bold" }), -- DiffText       xxx cterm=bold ctermbg=9 gui=bold guibg=Red
		SignColumn({ bg = "grey15", fg = "cyan" }), -- SignColumn     xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
		CursorLineSign({ SignColumn }), -- CursorLineSign xxx links to SignColumn
		Conceal({ bg = "darkgrey", fg = "lightgrey" }), -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=LightGrey guibg=DarkGrey
		SpellBad({ sp = "red", gui = "undercurl" }), -- SpellBad       xxx ctermbg=9 gui=undercurl guisp=Red
		ALEError({ SpellBad }), -- ALEError       xxx links to SpellBad
		SpellCap({ sp = "blue", gui = "undercurl" }), -- SpellCap       xxx ctermbg=12 gui=undercurl guisp=Blue
		ALEWarning({ SpellCap }), -- ALEWarning     xxx links to SpellCap
		SpellRare({ sp = "magenta", gui = "undercurl" }), -- SpellRare      xxx ctermbg=13 gui=undercurl guisp=Magenta
		SpellLocal({ sp = "cyan", gui = "undercurl" }), -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=Cyan
		Pmenu({ bg = "Grey30", fg = "Grey95" }), -- Pmenu          xxx ctermfg=0 ctermbg=13 guibg=Magenta
		NormalFloat({ Pmenu }), -- NormalFloat    xxx links to Pmenu
		PmenuSel({ bg = "red" }), -- PmenuSel       xxx ctermfg=242 ctermbg=0 guibg=DarkGrey
		PmenuSbar({ bg = "grey" }), -- PmenuSbar      xxx ctermbg=248 guibg=Grey
		PmenuThumb({ bg = "white" }), -- PmenuThumb     xxx ctermbg=15 guibg=White
		TabLine({ bg = "darkgrey", gui = "underline" }), -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 gui=underline guibg=DarkGrey
		TabLineSel({ gui = "bold" }), -- TabLineSel     xxx cterm=bold gui=bold
		netrwMarkFile({ TabLineSel }), -- netrwMarkFile  xxx links to TabLineSel
		TabLineFill({ gui = "reverse" }), -- TabLineFill    xxx cterm=reverse gui=reverse
		CursorColumn({ bg = "grey40" }), -- CursorColumn   xxx ctermbg=0 guibg=grey40
		CursorLine({ bg = "grey40" }), -- CursorLine     xxx cterm=underline guibg=grey40
		ColorColumn({ bg = "darkred" }), -- ColorColumn    xxx ctermbg=1 guibg=DarkRed
		MatchBackground({ ColorColumn }), -- MatchBackground xxx links to ColorColumn
		RedrawDebugNormal({ gui = "reverse" }), -- RedrawDebugNormal xxx cterm=reverse gui=reverse
		RedrawDebugClear({ bg = "yellow" }), -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
		RedrawDebugComposed({ bg = "green" }), -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
		RedrawDebugRecompose({ bg = "red" }), -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
		Cursor({ bg = "green", fg = "black" }), -- Cursor         xxx guifg=Black guibg=Green
		lCursor({ bg = "cyan", fg = "black" }), -- lCursor        xxx guifg=Black guibg=Cyan
		Normal({ bg = "grey15", fg = hsl("#FFFFFF") }), -- Normal         xxx ctermfg=15 ctermbg=242 guifg=White guibg=grey20
		NvimSpacing({ Normal }), -- NvimSpacing    xxx links to Normal
		FloatShadow({ blend = 80, bg = "black" }), -- FloatShadow    xxx guibg=Black blend=80
		FloatShadowThrough({ blend = 100, bg = "black" }), -- FloatShadowThrough xxx guibg=Black blend=100
		Error({ bg = "red", fg = "white" }), -- Error          xxx ctermfg=15 ctermbg=9 guifg=White guibg=Red
		NvimInvalid({ Error }), -- NvimInvalid    xxx links to Error
		luaParenError({ Error }), -- luaParenError  xxx links to Error
		luaBraceError({ Error }), -- luaBraceError  xxx links to Error
		luaError({ Error }), -- luaError       xxx links to Error
		ALEErrorSign({ Error }), -- ALEErrorSign   xxx links to Error
		ALESignColumnWithErrors({ Error }), -- ALESignColumnWithErrors xxx links to Error
		Todo({ bg = "yellow", fg = "blue" }), -- Todo           xxx ctermfg=0 ctermbg=11 guifg=Blue guibg=Yellow
		luaTodo({ Todo }), -- luaTodo        xxx links to Todo
		ALEWarningSign({ Todo }), -- ALEWarningSign xxx links to Todo
		Constant({ fg = "#ffa0a0" }), -- Constant       xxx ctermfg=13 guifg=#ffa0a0
		String({ fg = "#66cc00" }), -- String         xxx links to Constant
		Character({ Constant }), -- Character      xxx links to Constant
		Number({ Constant }), -- Number         xxx links to Constant
		Boolean({ fg = "#ff80ff" }), -- Boolean        xxx links to Constant
		luaConstant({ Constant }), -- luaConstant    xxx links to Constant
		Identifier({ fg = "#ff6d6d" }), -- Identifier     xxx cterm=bold ctermfg=14 guifg=#40ffff
		Function({ Identifier }), -- Function       xxx links to Identifier
		NvimIdentifier({ Identifier }), -- NvimIdentifier xxx links to Identifier
		netrwVersion({ Identifier }), -- netrwVersion   xxx links to Identifier
		luaFunc({ Identifier }), -- luaFunc        xxx links to Identifier
		Statement({ fg = "#ffff60" }), -- Statement      xxx cterm=bold ctermfg=11 gui=bold guifg=#ffff60
		Conditional({ fg = "#ff3333" }), -- Conditional    xxx links to Statement
		Repeat({ Statement }), -- Repeat         xxx links to Statement
		Label({ Statement }), -- Label          xxx links to Statement
		Operator({ Statement }), -- Operator       xxx links to Statement
		Keyword({ Statement }), -- Keyword        xxx links to Statement
		Exception({ Statement }), -- Exception      xxx links to Statement
		netrwHidePat({ Statement }), -- netrwHidePat   xxx links to Statement
		netrwList({ Statement }), -- netrwList      xxx links to Statement
		luaStatement({ Statement }), -- luaStatement   xxx links to Statement
		PreProc({ fg = "#ff80ff" }), -- PreProc        xxx ctermfg=81 guifg=#ff80ff
		Include({ PreProc }), -- Include        xxx links to PreProc
		Define({ PreProc }), -- Define         xxx links to PreProc
		Macro({ PreProc }), -- Macro          xxx links to PreProc
		PreCondit({ PreProc }), -- PreCondit      xxx links to PreProc
		netrwExe({ PreProc }), -- netrwExe       xxx links to PreProc
		Type({ fg = "Orange" }), --{ gui="bold", fg="#60ff60", }, -- Type           xxx ctermfg=121 gui=bold guifg=#60ff60
		StorageClass({ Type }), -- StorageClass   xxx links to Type
		Structure({ Type }), -- Structure      xxx links to Type
		Typedef({ Type }), -- Typedef        xxx links to Type
		NvimNumberPrefix({ Type }), -- NvimNumberPrefix xxx links to Type
		NvimOptionSigil({ Type }), -- NvimOptionSigil xxx links to Type
		Special({ fg = "orange" }), -- Special        xxx ctermfg=224 guifg=Orange
		Tag({ Special }), -- Tag            xxx links to Special
		SpecialChar({ Special }), -- SpecialChar    xxx links to Special
		Delimiter({ Special }), -- Delimiter      xxx links to Special
		SpecialComment({ Special }), -- SpecialComment xxx links to Special
		Debug({ Special }), -- Debug          xxx links to Special
		netrwLink({ Special }), -- netrwLink      xxx links to Special
		netrwTreeBar({ Special }), -- netrwTreeBar   xxx links to Special
		netrwPix({ Special }), -- netrwPix       xxx links to Special
		DiagnosticError({ fg = "red" }), -- DiagnosticError xxx ctermfg=1 guifg=Red
		DiagnosticVirtualTextError({ DiagnosticError }), -- DiagnosticVirtualTextError xxx links to DiagnosticError
		DiagnosticFloatingError({ DiagnosticError }), -- DiagnosticFloatingError xxx links to DiagnosticError
		DiagnosticSignError({ DiagnosticError }), -- DiagnosticSignError xxx links to DiagnosticError
		DiagnosticWarn({ fg = "orange" }), -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
		DiagnosticVirtualTextWarn({ DiagnosticWarn }), -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
		DiagnosticFloatingWarn({ DiagnosticWarn }), -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
		DiagnosticSignWarn({ DiagnosticWarn }), -- DiagnosticSignWarn xxx links to DiagnosticWarn
		DiagnosticInfo({ fg = "lightblue" }), -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
		DiagnosticVirtualTextInfo({ DiagnosticInfo }), -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
		DiagnosticFloatingInfo({ DiagnosticInfo }), -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
		DiagnosticSignInfo({ DiagnosticInfo }), -- DiagnosticSignInfo xxx links to DiagnosticInfo
		DiagnosticHint({ fg = "lightgrey" }), -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
		DiagnosticVirtualTextHint({ DiagnosticHint }), -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
		DiagnosticFloatingHint({ DiagnosticHint }), -- DiagnosticFloatingHint xxx links to DiagnosticHint
		DiagnosticSignHint({ DiagnosticHint }), -- DiagnosticSignHint xxx links to DiagnosticHint
		DiagnosticUnderlineError({ sp = "red", gui = "underline" }), -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
		DiagnosticUnderlineWarn({ sp = "orange", gui = "underline" }), -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
		DiagnosticUnderlineInfo({ sp = "lightblue", gui = "underline" }), -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
		DiagnosticUnderlineHint({ sp = "lightgrey", gui = "underline" }), -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
		MatchParen({ bg = "darkcyan" }), -- MatchParen     xxx ctermbg=6 guibg=DarkCyan
		MatchParenCur({ MatchParen }), -- MatchParenCur  xxx links to MatchParen
		MatchWord({ MatchParen }), -- MatchWord      xxx links to MatchParen
		Comment({ fg = "grey75" }), -- Comment        xxx ctermfg=14 guifg=#80a0ff
		netrwComment({ Comment }), -- netrwComment   xxx links to Comment
		luaComment({ Comment }), -- luaComment     xxx links to Comment
		Underlined({ gui = "underline", fg = "#80a0ff" }), -- Underlined     xxx cterm=underline ctermfg=81 gui=underline guifg=#80a0ff
		Ignore({ fg = "grey20" }), -- Ignore         xxx ctermfg=242 guifg=grey20
		NvimInternalError({ bg = "red", fg = "red" }), -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
		NvimFigureBrace({ NvimInternalError }), -- NvimFigureBrace xxx links to NvimInternalError
		NvimSingleQuotedUnknownEscape({ NvimInternalError }), -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
		NvimInvalidSingleQuotedUnknownEscape({ NvimInternalError }), -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
		ALESignColumnWithoutErrors({ bg = "grey", fg = "cyan" }), -- ALESignColumnWithoutErrors xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
		colorizer_mb_aa33cc({ bg = "#aa33cc", fg = "white" }), -- colorizer_mb_aa33cc xxx guifg=White guibg=#aa33cc
		colorizer_mb_a3cff5({ bg = "#a3cff5", fg = "black" }), -- colorizer_mb_a3cff5 xxx guifg=Black guibg=#a3cff5
		colorizer_mb_a3bff5({ bg = "#a3bff5", fg = "black" }), -- colorizer_mb_a3bff5 xxx guifg=Black guibg=#a3bff5
		colorizer_mb_a1bff5({ bg = "#a1bff5", fg = "black" }), -- colorizer_mb_a1bff5 xxx guifg=Black guibg=#a1bff5
	}
end)
return theme
